version: '3.7'

services:

  swagger-editor:
    build: ./swagger-editor
    volumes:
      - ./yaml:/swagger-yaml
    ports:
      - 81:8080

  swagger-ui:
    build: ./swagger-ui
    volumes:
      - ./yaml:/swagger-yaml
    ports:
      - 80:8080

